### ISSUE TITLE
특정 엔드포인트에서 값이 잘못 반환됨

### ISSUE THREAD

**Issue by Astro-CQM** [Saebasol/Heliotrope#177]
### Please explain the bug.

기존에 /api/hitomi/random 엔드포인트를 호출 시 thumbnail 항목을 url로 지급했지만, 현재 hash 값이 포함된 dict를 돌려보냄.

### How can I reproduce it?

GET https://api.saebasol.org/api/hitomi/random

응답 중 thumbnail 값

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaidBySolo** [comment]
Same can be reproduced on the ``GET`` ``api/hitomi/list/1`` endpoint
