### ISSUE TITLE
How often does the API update the source data ?

### ISSUE THREAD

**Issue by FluffyDiscord** [Saebasol/Heliotrope#252]
The title, since on quick glance I see only 2-3 days old galleries when using the search endpoint

**Comment by SaidBySolo** [comment]
Thank you for your interest in our api.

[Mirror every hour.](https://github.com/Saebasol/Heliotrope/blob/e4c93189ca520a0b24ea3c914780abe1f1bfd8ad/heliotrope/config.py#L53)

However, only [Korean works are mirrored in the API](https://github.com/Saebasol/Heliotrope/blob/e4c93189ca520a0b24ea3c914780abe1f1bfd8ad/heliotrope/config.py#L52) provided by api.saebasol.org.

Users can solve this by changing the config value and then deploying it, but

I would also consider getting an up-to-date list of other languages ​​from api.saebasol.org.

**Comment by FluffyDiscord** [comment]
Aha, that would explain things, would it be possible to expand to all languages ? The storage requiremenets would probably skyrocket for you...

Or I think the other most used languages would be **English, Japanese** and **Chinese**, the other ones mostly take up from these

**Comment by SaidBySolo** [comment]
It is possible, but need to filter by language.

We'll put this on the 6.1.x milestone.

**Comment by SaidBySolo** [comment]
@FluffyDiscord 

A total of 531401 works have just been mirrored.

Hope you have a great experience!
