### ISSUE TITLE
Search endpoint seems broken - error 500 or empty results

### ISSUE THREAD

**Issue by FluffyDiscord** [Saebasol/Heliotrope#259]
### Please explain the bug.

Example API at https://api.saebasol.org/docs behaves weirdly

### How can I reproduce it?

This request works, but returns nothing
```
{
  "offset": 1,
  "query": [
    "female:loli-all"
  ]
}
```

The following request throws error 500
```
curl -X 'POST' \
  'https://api.saebasol.org/api/hitomi/search' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "offset": 1,
  "query": [
    "female:loli"
  ]
}'
```

### Heliotrope version or Docker image version

```console
API version: 6.2.7
```

### Additional Description

On a side note - this is not a bug per say, but rather random finding that may, or may not, correspond with the errors above.

Sending request
```
curl -X 'POST' \
  'https://api.saebasol.org/api/hitomi/search' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "offset": 1,
  "query": [
    "female:loli-all",
  ],
  "language":"english"
}'
```

results into receiving html

![pic](https://user-images.githubusercontent.com/10332247/182958763-7cddc214-bfdf-469a-9c1d-8a2dd7d5855c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaidBySolo** [comment]
The second seems to be a problem caused by not parsing the json.

 commas in "female:loli-all" in the query.

But let's find a way to handle this.

**Comment by FluffyDiscord** [comment]
> The second seems to be a problem caused by not parsing the json.
> 
> commas in "female:loli-all" in the query.
> 
> But let's find a way to handle this.

So the first result is correct? I thought we should be search by the tags and don't add the "-all" suffix

**Comment by SaidBySolo** [comment]
> > The second seems to be a problem caused by not parsing the json.
> > commas in "female:loli-all" in the query.
> > But let's find a way to handle this.
> 
> So the first result is correct? I thought we should be search by the tags and don't add the "-all" suffix

-all suffix is wrong.

```
curl -X 'POST' \
  'https://api.saebasol.org/api/hitomi/search' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "offset": 1,
  "query": [
    "female:loli"
  ]
}'
```
The query is correct, but an error occurred because the memory limit for sorting by mongodb was exceeded, resulting in a 500 error. Reported to Sentry and plans to fix it.
