### ISSUE TITLE
search endpoint seems to still run out of memory if the offset is over a certain threshold

### ISSUE THREAD

**Issue by FluffyDiscord** [Saebasol/Heliotrope#276]
### Please explain the bug.

Searching over a certain offset throws error 500.

### How can I reproduce it?

this works (at the time of reporting)

curl -X 'POST' \
  'https://api.saebasol.org/api/hitomi/search' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "offset": 7800,
  "query": [
    "female:loli"
  ]
}'

but this throws error 500  (at the time of reporting)

curl -X 'POST' \
  'https://api.saebasol.org/api/hitomi/search' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "offset": 7810,
  "query": [
    "female:loli"
  ]
}'

### Heliotrope version or Docker image version

```console
6.3.6 at https://api.saebasol.org/docs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaidBySolo** [comment]
Ok let's use the ``allowdiskuse`` option

**Comment by SaidBySolo** [comment]
Related #259
