### ISSUE TITLE
https://api.saebasol.org/docs is down

### ISSUE THREAD

**Issue by FluffyDiscord** [Saebasol/Heliotrope#327]
### Please explain the bug.

The API page is down.

### How can I reproduce it?

Visit https://api.saebasol.org/docs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Astro-CQM** [comment]
Not a bug, It is under maintenance now.

**Comment by SaidBySolo** [comment]
We will be releasing 7.0.0 experimentally next month.

**Comment by FluffyDiscord** [comment]
Ah, okay. Thank you for your work👍

**Comment by FluffyDiscord** [comment]
Any updates on this?

**Comment by SaidBySolo** [comment]
@FluffyDiscord 

I'm configuring it via docker swarm. Maybe this week I will start mirroring, apply rate limits and deploy

**Comment by FluffyDiscord** [comment]
Any updates on this?

**Comment by Astro-CQM** [comment]
> Any updates on this?

It was up for few days, but it is down again. maybe you can self-host this repository if you want to use the API.
