### ISSUE TITLE
How to install/use?

### ISSUE THREAD

**Issue by Ruriko** [Saebasol/Heliotrope#34]
May I have instructions on how to install the api? and is there a doc with the api parameters?

**Comment by SaidBySolo** [comment]
Currently v5 is not ready for deployment.

v4 can be accessed at https://github.com/Saebasol/Heliotrope_deprecated/pkgs/container/Heliotrope%2Fheliotrope

please refer to that link for the endpoint

https://github.com/Saebasol/Mintchoco_deprecated/blob/master/mintchoco/client.py#L61

simple endpoint: https://heliotrope/v4/api/hitomi/galleryinfo/1496588
Currently, only Korean works are supported.

**Comment by Ruriko** [comment]
will v5 support Japanese works?

**Comment by SaidBySolo** [comment]
If implemented, it will not be cached in the database.

Let's add it to Todo.
